// USER ACTION-TYPES
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const USER_GET_ME = 'USER_GET_ME';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAILURE = 'USER_UPDATE_PROFILE_FAILURE';

// NOTES ACTION-TYPES
export const GET_NOTES = 'GET_NOTES';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_FAILURE = 'GET_NOTES_FAILURE';
// START A NEW NOTE
export const ADD_NEW_NOTE = 'ADD_NEW_NOTE';
export const ADD_NEW_NOTE_SUCCESS = 'ADD_NEW_NOTE_SUCCESS';
export const ADD_NEW_NOTE_FAILURE = 'ADD_NEW_NOTE_FAILURE';
// Update AN EXISTING NOTE
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_ZINDEX = 'UPDATE_ZINDEX';
// UPDATE LOCATION OF A NOTE
export const UPDATE_LOCATION          = 'UPDATE_LOCATION';
export const UPDATE_LOCATION_SUCCESS  = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAILURE  = 'UPDATE_LOCATION_FAILURE';

